# Site settings
title: Speicher Dein Strom
description: "Kostengünstige Speichersysteme für Ihren Photovoltaik Strom" # this means to ignore newlines until "baseurl:"
repository: vvalchev/creative-theme-jekyll-new
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Copyright &copy; 2023 - Dipl.-Ing. Thomas Wetterer
lang: de_DE

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
defaults:
  - scope:
      path: ""
      type: "pages" 
    values:
      layout: "page" # overrides previous default layout
